steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service1:${SHORT_SHA}'
      - '-f'
      - 'browser-use-dev/Dockerfile'
      - './browser-use-dev'
    id: 'build-browser-use'

  # # Build Image 2
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'build'
  #     - '-t'
  #     - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service2:${SHORT_SHA}'
  #     - '-f'
  #     - './service2/Dockerfile'
  #     - './service2'
  #   id: 'build-service2'

  # # Build Image 3
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'build'
  #     - '-t'
  #     - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service3:${SHORT_SHA}'
  #     - '-f'
  #     - './service3/Dockerfile'
  #     - './service3'
  #   id: 'build-service3'

  # Push Image 1 to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service1:${SHORT_SHA}'
    id: 'browser-use'
    waitFor: ['build-browser-use']

  # # Push Image 2 to Artifact Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'push'
  #     - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service2:${SHORT_SHA}'
  #   id: 'push-service2'
  #   waitFor: ['build-service2']

  # # Push Image 3 to Artifact Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'push'
  #     - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service3:${SHORT_SHA}'
  #   id: 'push-service3'
  #   waitFor: ['build-service3']
logsBucket: 'agentic-prior-storage-bucket'
options:
  logging: GCS_ONLY

  