steps:
  # Build Image 1
  - name: 'docker/compose:1.26.2'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service1:${SHORT_SHA}'
      - '-f'
      - './browser-use-dev/docker-compose.yml'
      - './browser-use-dev'
    id: 'build-browser-use'

  # Build Image 2
  - name: 'docker/compose:1.26.2'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service2:${SHORT_SHA}'
      - '-f'
      - './n8n/docker-compose.yml'
      - './n8n'
    id: 'build-n8n'

  # Build Image 3
  - name: 'docker/compose:1.26.2'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service3:${SHORT_SHA}'
      - '-f'
      - './planner-adk/docker-compose.yml'
      - './planner-adk'
    id: 'build-planner-adk'
    # Build Image 3
  - name: 'docker/compose:1.26.2'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service3:${SHORT_SHA}'
      - '-f'
      - './planner-backend/docker-compose.yml'
      - './planner-backend'
    id: 'build-planner-backend'

  # Push Image 1 to Artifact Registry
  - name: 'docker/compose:1.26.2'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service1:${SHORT_SHA}'
    id: 'push-browser-use'
    waitFor: ['build-browser-use']

  # Push Image 2 to Artifact Registry
  - name: 'docker/compose:1.26.2'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service2:${SHORT_SHA}'
    id: 'push-n8n'
    waitFor: ['build-n8n']

  # Push Image 3 to Artifact Registry
  - name: 'docker/compose:1.26.2'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service3:${SHORT_SHA}'
    id: 'push-planner-adk'
    waitFor: ['build-planner-adk']
    # Push Image 3 to Artifact Registry
  - name: 'docker/compose:1.26.2'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/service3:${SHORT_SHA}'
    id: 'push-planner-backend'
    waitFor: ['build-planner-backend']
options:
  logging: CLOUD_LOGGING_ONLY

  