apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  annotations:
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/description: "Multi-container service with 4 applications"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "2"
        autoscaling.knative.dev/minScale: "1"
    spec:
      # Service timeout (maximum request duration)
      timeoutSeconds: 300
      
      # Container concurrency (requests per instance)
      containerConcurrency: 100
      
      containers:
        # Main container (BROWSER) - receives external traffic
        - name: main-service
          image: {{browser-use}}
          ports:
            - name: http1
              containerPort: {{BROWSER_PORT}}
          resources:
            limits:
              memory: {{BROWSER_MEMORY}}
              cpu: {{BROWSER_CPU}}
          env:
            - name: SERVICE_TYPE
              value: "main"
            - name: PORT
              value: "{{BROWSER_PORT}}"
            - name: N8N_URL
              value: "http://localhost:{{N8N_PORT}}"
            - name: PLANNERADK_URL
              value: "http://localhost:{{PLANNERADK_PORT}}"
          # Health check configuration
          livenessProbe:
            httpGet:
              path: /health
              port: {{BROWSER_PORT}}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: {{BROWSER_PORT}}
            initialDelaySeconds: 5
            periodSeconds: 5

        # Sidecar container 1 (N8N)
        - name: sidecar-N8N
          image: {{N8N_IMAGE}}
          ports:
            - name: http2
              containerPort: {{N8N_PORT}}
          resources:
            limits:
              memory: {{N8N_MEMORY}}
              cpu: {{N8N_CPU}}
          env:
            - name: SERVICE_TYPE
              value: "sidecar2"
            - name: PORT
              value: "{{N8N_PORT}}"
            - name: MAIN_SERVICE_URL
              value: "http://localhost:{{BROWSER_PORT}}"
            - name: PLANNERADK_URL
              value: "http://localhost:{{PLANNERADK_PORT}}"

        # Sidecar container 2 (PLANNERADK)
        - name: sidecar-PLANNERADK
          image: {{PLANNERADK_IMAGE}}
          ports:
            - name: http3
              containerPort: {{PLANNERADK_PORT}}
          resources:
            limits:
              memory: {{PLANNERADK_MEMORY}}
              cpu: {{PLANNERADK_CPU}}
          env:
            - name: SERVICE_TYPE
              value: "sidecar3"
            - name: PORT
              value: "{{PLANNERADK_PORT}}"
            - name: MAIN_SERVICE_URL
              value: "http://localhost:{{BROWSER_PORT}}"
            - name: N8N_URL
              value: "http://localhost:{{N8N_PORT}}"
   # Sidecar container 2 (PLANNERADK)
        - name: sidecar-PLANNERBACKEND
          image: {{PLANNERBACKEND_IMAGE}}
          ports:
            - name: http3
              containerPort: {{PLANNERBACKEND_PORT}}
          resources:
            limits:
              memory: {{PLANNERBACKEND_MEMORY}}
              cpu: {{PLANNERBACKEND_CPU}}
          env:
            - name: SERVICE_TYPE
              value: "sidecar3"
            - name: PORT
              value: "{{PLANNERADK_PORT}}"
            - name: MAIN_SERVICE_URL
              value: "http://localhost:{{BROWSER_PORT}}"
            - name: N8N_URL
              value: "http://localhost:{{PLANNERADK_PORT}}"