apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  annotations:
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/description: "Multi-container service with 4 images"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "2"
        autoscaling.knative.dev/minScale: "1"
    spec:
      # Service timeout (maximum request duration)
      timeoutSeconds: 300
      
      # Container concurrency (requests per instance)
      containerConcurrency: 100
      containers:
        # Main container (planner-adk) - receives external traffic
        - name: main-service
          image: {{planner-adk}}
          ports:
            - name: http1
              containerPort: "{{PLANNERADK_PORT}}"
          resources:
            limits:
              memory: "{{PLANNERADK_PORT}}"
              cpu: "{{PLANNERADK_CPU}}"
          env:
            - name: SERVICE_TYPE
              value: "planner-adk"
            - name: PORT
              value: "{{PLANNERADK_PORT}}"
            - name: N8N_URL
              value: "http://localhost:{{N8N_PORT}}"
            - name: BROWSER_URL
              value: "http://localhost:{{BROWSER_PORT}}"
            - name: PLANNERBACKEND_URL
              value: "http://localhost:{{PLANNERBACKEND_PORT}}"
          # Health check configuration
          livenessProbe:
            httpGet:
              path: /health
              port: "{{PLANNERADK_PORT}}"
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: "{{PLANNERADK_PORT}}"
            periodSeconds: 5
            # Sidecar container 1 (N8N)
        - name: sidecar-n8n
          image: {{n8n}}
          ports:
              containerPort: "{{N8N_PORT}}"
          resources:
            limits:
              memory: "{{N8N_MEMORY}}"
              cpu: "{{N8N_CPU}}"
          env:
            - name: SERVICE_TYPE
              value: "n8n"
            - name: PORT
              value: "{{N8N_PORT}}"
            # - name: MAIN_SERVICE_URL
            #   value: "http://localhost:{{BROWSER_PORT}}"
            # - name: PLANNERADK_URL
            #   value: "http://localhost:{{PLANNERADK_PORT}}"
            # - name: PLANNERBACKEND_URL
            #   value: "http://localhost:{{PLANNERBACKEND_PORT}}"
        # Sidecar container 2 (BROWSER)
        - name: sidecar-browser-use
          image: {{browser-use}}
          ports:
              containerPort: "{{BROWSER_PORT}}"
          resources:
            limits:
              memory: "{{BROWSER_MEMORY}}"
              cpu: "{{BROWSER_CPU}}"
          env:
            - name: SERVICE_TYPE
              value: "browser-use"
            - name: PORT
              value: "{{BROWSER_PORT}}"
            # - name: MAIN_SERVICE_URL
            #   value: "http://localhost:{{PLANNERADK_PORT}}"
            # - name: N8N_URL
            #   value: "http://localhost:{{N8N_PORT}}"
            # - name: PLANNERBACKEND_URL
            #   value: "http://localhost:{{PLANNERBACKEND_PORT}}"
              # Sidecar container 3 (PLANNERBACKEND)
        - name: sidecar-plannerbackend
          image: {{planner-backend}}
          ports:
              containerPort: "{{PLANNERBACKEND_PORT}}"
          resources:
            limits:
              memory: "{{PLANNERBACKEND_MEMORY}}"
              cpu: "{{PLANNERBACKEND_CPU}}"
          env:
            - name: SERVICE_TYPE
              value: "plannerbackend"
            - name: PORT
              value: "{{PLANNERBACKEND_PORT}}"
            # - name: MAIN_SERVICE_URL
            #   value: "http://localhost:{{BROWSER_PORT}}"
            # - name: N8N_URL
            #   value: "http://localhost:{{N8N_PORT}}"
            # - name: PLANNERADK_URL
            #   value: "http://localhost:{{PLANNERADK_PORT}}"
