apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  annotations:
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/description: "Multi-container service with 4 images"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "2"
        autoscaling.knative.dev/minScale: "1"
        
    spec:
      # Service timeout (maximum request duration)
      timeoutSeconds: 3600
      
      # Container concurrency (requests per instance)
      containerConcurrency: 100
      containers:
        # Main container (planner-adk) - receives external traffic
        - name: planner-adk
          image: {{planner-adk}}
          ports:
            - name: http1
              containerPort: "{{PLANNERADK_PORT}}"
          resources:
            limits:
              memory: "{{PLANNERADK_MEMORY}}"
              cpu: "{{PLANNERADK_CPU}}"
            requests:
              memory: "1Gi"
              cpu: "0.5"
          env:
            - name: SERVICE_TYPE
              value: "planner-adk"
            - name: DEBUG_MODE
              value: "true"
          # Health check configuration
          livenessProbe:
            httpGet:
              path: /health
              port: "{{PLANNERADK_PORT}}"
            periodSeconds: 100
          startupProbe:
            tcpSocket:
              port: "{{PLANNERADK_PORT}}"
            periodSeconds: 2
            failureThreshold: 180