version: "3.9"

services:
  customer-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-agent
    environment:
      GOOGLE_GENAI_USE_VERTEXAI: ${GOOGLE_GENAI_USE_VERTEXAI}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      BASE_URL: ${BASE_URL}
    ports:
      - "8002:8002"
    restart: unless-stopped
