version: '3.8'

services:
  app:
    build:
      context: .
    container_name: browser-use-api
    environment:
      - OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - BASE_URL=${BASE_URL}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - BLOB_CONTAINER_NAME=${BLOB_CONTAINER_NAME}
      - DEFAULT_LLM=${DEFAULT_LLM}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CAP_SOLVER_API=${CAP_SOLVER_API}
      - ALGORITHM=${ALGORITHM}
      - SECRET_KEY=${SECRET_KEY}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
    volumes:
      - ./app/extensions/capsolver:/app/extensions/capsolver
    ports:
      - "8000:8000"
      - "5901-5999:5901-5999"
      - "6081-6199:6081-6199"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    logging:
      driver: "none"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
